<?php
require __DIR__.'/includes/bootstrap.php';require_login();
$type=$_REQUEST['type']??'';$amount=0;$item='';$context=[];$error='';$qty=max(1,min(20,(int)($_REQUEST['nb']??1)));
try{
 if($type==='hotel'){$id=(int)($_REQUEST['room_id']??0);$a=$_REQUEST['arrivee']??'';$d=$_REQUEST['depart']??'';$n=max(1,(int)($_REQUEST['personnes']??1));$st=$pdo->prepare('SELECT r.*,h.nom hotel,h.ville FROM rooms r JOIN hotels h ON h.id=r.hotel_id WHERE r.id=? AND r.disponible=1 AND h.actif=1');$st->execute([$id]);$r=$st->fetch();if(!$r||!$a||!$d||$a<date('Y-m-d')||$d<=$a||$n>$r['capacite'])throw new RuntimeException('Dates ou chambre invalides.');$nights=(int)((strtotime($d)-strtotime($a))/86400);$amount=(int)$r['prix_nuit']*$nights;$item=$r['hotel'].' — '.$r['type'];$context=compact('id','a','d','n','nights');}
 elseif($type==='billet'){$id=(int)($_REQUEST['schedule_id']??0);$st=$pdo->prepare('SELECT s.*,r.* FROM trips_schedule s JOIN routes r ON r.id=s.route_id WHERE s.id=? AND s.date_depart>=CURDATE() AND r.actif=1');$st->execute([$id]);$r=$st->fetch();if(!$r||$qty>$r['places_restantes'])throw new RuntimeException('Départ ou nombre de places invalide.');$amount=$qty*(int)$r['prix'];$item=$r['origine'].' → '.$r['destination'];$context=compact('id','qty');}
 elseif($type==='forfait'){$id=(int)($_REQUEST['package_id']??0);$dep=(int)($_REQUEST['date']??0);$st=$pdo->prepare('SELECT p.*,d.date_depart,d.places FROM packages p JOIN package_departures d ON d.package_id=p.id WHERE p.id=? AND d.id=? AND d.date_depart>=CURDATE() AND p.actif=1');$st->execute([$id,$dep]);$r=$st->fetch();if(!$r||$qty>$r['places'])throw new RuntimeException('Départ ou nombre de participants invalide.');$amount=$qty*(int)$r['prix'];$item=$r['titre'];$context=['id'=>$id,'dep'=>$dep,'qty'=>$qty,'date'=>$r['date_depart']];}
 else throw new RuntimeException('Type de réservation inconnu.');
}catch(Throwable $e){$error=$e->getMessage();}
if($_SERVER['REQUEST_METHOD']==='POST'&&!$error){verify_csrf();$method=$_POST['methode']??'';if(!in_array($method,['orange_money','mtn_momo','carte'],true))$error='Choisissez un moyen de paiement.';else{try{$pdo->beginTransaction();$ref='VY'.strtoupper(bin2hex(random_bytes(6)));
 if($type==='hotel'){$s=$pdo->prepare("SELECT id FROM rooms WHERE id=? AND disponible=1 AND NOT EXISTS(SELECT 1 FROM room_bookings b WHERE b.room_id=rooms.id AND b.statut IN ('en_attente','confirmee','payee') AND b.date_arrivee<? AND b.date_depart>?) FOR UPDATE");$s->execute([$context['id'],$context['d'],$context['a']]);if(!$s->fetch())throw new RuntimeException('Cette chambre vient d’être réservée pour ces dates.');$s=$pdo->prepare("INSERT INTO room_bookings(room_id,user_id,date_arrivee,date_depart,nb_personnes,prix_total,statut) VALUES(?,?,?,?,?,?,'payee')");$s->execute([$context['id'],user()['id'],$context['a'],$context['d'],$context['n'],$amount]);$booking=(int)$pdo->lastInsertId();}
 elseif($type==='billet'){$s=$pdo->prepare('UPDATE trips_schedule SET places_restantes=places_restantes-? WHERE id=? AND places_restantes>=?');$s->execute([$context['qty'],$context['id'],$context['qty']]);if(!$s->rowCount())throw new RuntimeException('Il ne reste plus assez de places.');$s=$pdo->prepare("INSERT INTO ticket_bookings(schedule_id,user_id,nb_billets,prix_total,statut,code_billet) VALUES(?,?,?,?, 'payee',?)");$s->execute([$context['id'],user()['id'],$context['qty'],$amount,$ref]);$booking=(int)$pdo->lastInsertId();}
 else{$s=$pdo->prepare('UPDATE package_departures SET places=places-? WHERE id=? AND places>=?');$s->execute([$context['qty'],$context['dep'],$context['qty']]);if(!$s->rowCount())throw new RuntimeException('Il ne reste plus assez de places.');$s=$pdo->prepare("INSERT INTO package_bookings(package_id,departure_id,user_id,nb_participants,date_depart_choisie,prix_total,statut) SELECT ?,?, ?, ?,date_depart,?,'payee' FROM package_departures WHERE id=?");$s->execute([$context['id'],$context['dep'],user()['id'],$context['qty'],$amount,$context['dep']]);$booking=(int)$pdo->lastInsertId();}
 $s=$pdo->prepare("INSERT INTO payments(booking_type,booking_id,montant,methode,statut,reference_transaction) VALUES(?,?,?,?, 'reussi',?)");$s->execute([$type,$booking,$amount,$method,$ref]);$pdo->commit();redirect('/dashboard.php?success=1');
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}}}
$title='Finaliser ma réservation';require __DIR__.'/includes/header.php';?>
<section class="max-w-6xl mx-auto px-4 pb-12"><div class="page-heading"><p class="page-eyebrow">Réservation Voyalo</p><h1 class="page-title">Finalisez votre réservation</h1><div class="checkout-steps"><span>1 · Votre choix</span><span class="current">2 · Paiement</span><span>3 · Confirmation</span></div></div>
<?php if($error):?><div class="empty-state"><strong class="text-slate-800"><?=e($error)?></strong><p class="mt-2">Vérifiez les disponibilités puis relancez votre recherche.</p><a class="btn mt-4" href="javascript:history.back()">Retour aux résultats</a></div><?php else:?>
<div class="grid lg:grid-cols-[minmax(0,1fr)_360px] gap-5"><form method="post" class="detail-section"><input type="hidden" name="type" value="<?=e($type)?>"><?php foreach($_GET as $k=>$v):?><input type="hidden" name="<?=e($k)?>" value="<?=e((string)$v)?>"><?php endforeach;?><?=csrf_field()?>
<p class="page-eyebrow">Étape 2 sur 3</p><h2 class="text-xl font-black mt-1">Choisissez votre moyen de paiement</h2><p class="text-sm text-slate-600 mt-2">Sélectionnez une option pour confirmer votre réservation.</p><div class="space-y-2 mt-5"><?php foreach(['orange_money'=>'Orange Money','mtn_momo'=>'MTN Mobile Money','carte'=>'Carte bancaire'] as $k=>$v):?><label class="payment-option"><input type="radio" name="methode" value="<?=$k?>" required><span><strong><?=e($v)?></strong><small class="block text-slate-500">Paiement sécurisé · <?= $k==='carte'?'Visa / Mastercard':'Paiement mobile' ?></small></span></label><?php endforeach;?></div><p class="mt-5 text-xs text-orange-800 bg-orange-50 p-3 rounded-lg">Mode démonstration : aucun débit réel ne sera effectué.</p><button class="btn w-full mt-5">Confirmer et payer <?=money($amount)?></button><p class="text-xs text-center text-slate-500 mt-3">En confirmant, vous acceptez les conditions de réservation Voyalo.</p></form>
<aside class="detail-section h-fit"><p class="page-eyebrow">Récapitulatif</p><h2 class="font-black text-lg mt-1"><?=e($item)?></h2><div class="border-t mt-4 pt-4 space-y-2 text-sm text-slate-600"><?php if($type==='hotel'):?><p>Arrivée <strong class="float-right text-slate-800"><?=date('d/m/Y',strtotime($context['a']))?></strong></p><p>Départ <strong class="float-right text-slate-800"><?=date('d/m/Y',strtotime($context['d']))?></strong></p><p><?=$context['nights']?> nuit(s) · <?=$context['n']?> voyageur(s)</p><?php elseif($type==='billet'):?><p><?=$context['qty']?> billet(s)</p><?php else:?><p>Départ <?=date('d/m/Y',strtotime($context['date']))?></p><p><?=$context['qty']?> participant(s)</p><?php endif;?></div><div class="border-t mt-4 pt-4 flex justify-between"><strong>Total à payer</strong><strong class="text-teal-800 text-lg"><?=money($amount)?></strong></div><p class="text-xs text-slate-500 mt-2">Taxes incluses · Montant en FCFA</p></aside></div><?php endif;?></section><?php require __DIR__.'/includes/footer.php';?>
