<?php
require __DIR__.'/includes/bootstrap.php';
$city=trim($_GET['ville']??'');$arrival=$_GET['arrivee']??'';$departure=$_GET['depart']??'';$people=max(1,(int)($_GET['personnes']??1));$budget=max(0,(int)($_GET['budget']??0));$stars=max(0,min(5,(int)($_GET['etoiles']??0)));
$sql="SELECT h.*,MIN(r.prix_nuit) prix_nuit,COALESCE(AVG(rv.note),0) note,COUNT(DISTINCT rv.id) avis FROM hotels h JOIN rooms r ON r.hotel_id=h.id AND r.disponible=1 LEFT JOIN reviews rv ON rv.hotel_id=h.id WHERE h.actif=1 AND r.capacite>=?";$args=[$people];if($city!==''){$sql.=' AND h.ville LIKE ?';$args[]='%'.$city.'%';}if($budget>0){$sql.=' AND r.prix_nuit<=?';$args[]=$budget;}if($stars){$sql.=' AND h.etoiles>=?';$args[]=$stars;}if($arrival&&$departure&&$arrival<$departure){$sql.=" AND EXISTS(SELECT 1 FROM rooms ar WHERE ar.hotel_id=h.id AND ar.disponible=1 AND ar.capacite>=? AND NOT EXISTS(SELECT 1 FROM room_bookings b WHERE b.room_id=ar.id AND b.statut IN ('en_attente','confirmee','payee') AND b.date_arrivee<? AND b.date_depart>?))";$args[]=$people;$args[]=$departure;$args[]=$arrival;}$sql.=' GROUP BY h.id ORDER BY h.etoiles DESC';$s=$pdo->prepare($sql);$s->execute($args);$hotels=$s->fetchAll();$found=count($hotels);$title='Hébergements au Cameroun';require __DIR__.'/includes/header.php';
?>
<section class="max-w-7xl mx-auto px-4 pb-10">
  <div class="page-heading"><p class="page-eyebrow">Hébergements · Cameroun</p><h1 class="page-title">Trouvez votre prochain séjour</h1><p class="page-subtitle">Comparez les hébergements et choisissez celui qui vous convient.</p></div>
  <form class="booking-search" method="get"><div><label>Destination</label><input name="ville" value="<?=e($city)?>" placeholder="Douala, Kribi…"></div><div><label>Arrivée</label><input type="date" name="arrivee" value="<?=e($arrival)?>"></div><div><label>Départ</label><input type="date" name="depart" value="<?=e($departure)?>"></div><div><label>Voyageurs</label><input type="number" min="1" name="personnes" value="<?=$people?>"></div><input type="hidden" name="budget" value="<?=$budget?>"><input type="hidden" name="etoiles" value="<?=$stars?>"><button class="btn">Rechercher</button></form>
  <div class="list-layout">
    <form class="filter-panel" method="get"><h2>Filtrer les résultats</h2><p class="text-sm text-slate-500">Affinez votre recherche</p><input type="hidden" name="ville" value="<?=e($city)?>"><input type="hidden" name="arrivee" value="<?=e($arrival)?>"><input type="hidden" name="depart" value="<?=e($departure)?>"><input type="hidden" name="personnes" value="<?=$people?>"><div class="filter-group"><label for="budget">Prix maximum par nuit</label><input id="budget" name="budget" type="number" min="0" step="5000" placeholder="Sans limite" value="<?=$budget?:''?>"><button class="btn w-full mt-3">Appliquer</button></div><div class="filter-group"><strong class="text-sm">Catégorie</strong><?php for($i=5;$i>=1;$i--):?><label class="flex items-center gap-2"><input type="radio" name="etoiles" value="<?=$i?>" <?=$stars===$i?'checked':''?>> <?=str_repeat('★',$i)?></label><?php endfor;?><label class="flex items-center gap-2"><input type="radio" name="etoiles" value="0" <?=$stars===0?'checked':''?>> Toutes les catégories</label></div><div class="filter-group text-sm text-slate-600">Prix affichés en FCFA.<br>La disponibilité est vérifiée selon vos dates.</div></form>
    <div><div class="result-topline"><p class="result-count"><strong><?=$found?></strong> hébergement<?=$found===1?'':'s'?> trouvé<?=$found===1?'':'s'?><?= $city?' à '.e($city):'' ?></p><span class="text-sm text-slate-500">Tri : recommandés</span></div>
      <div class="result-list"><?php foreach($hotels as $h):?><article class="stay-card"><img loading="lazy" src="<?=e($h['image_principale']?:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80')?>" alt="Hôtel <?=e($h['nom'])?>"><div class="stay-content"><div><div class="flex gap-2 items-center"><h2 class="stay-title"><?=e($h['nom'])?></h2><span class="pill"><?=str_repeat('★',(int)$h['etoiles'])?></span></div><p class="stay-location">⌖ <?=e($h['ville'])?> · <?=e($h['adresse'])?></p><p class="stay-description"><?=e($h['description'])?></p><p class="stay-rate"><?php if($h['avis']):?><span class="pill"><?=number_format((float)$h['note'],1)?> / 5</span> · <?=$h['avis']?> avis<?php else:?>Hébergement partenaire Voyalo<?php endif;?></p></div><div class="stay-price"><small>À partir de</small><strong><?=money($h['prix_nuit'])?></strong><small>par nuit</small><a class="btn" href="/hotel-detail.php?id=<?=(int)$h['id']?>&arrivee=<?=e($arrival)?>&depart=<?=e($departure)?>&personnes=<?=$people?>">Voir les chambres</a></div></div></article><?php endforeach;?><?php if(!$hotels):?><div class="empty-state"><strong class="text-slate-800">Aucun hébergement trouvé</strong><p class="mt-2">Essayez d'autres dates ou élargissez votre budget.</p><a class="btn mt-4" href="/hotels.php">Effacer les filtres</a></div><?php endif;?></div>
    </div>
  </div>
</section><?php require __DIR__.'/includes/footer.php';?>
