<?php
require __DIR__.'/../includes/bootstrap.php';require_role(['admin']);
$kind=$_GET['kind']??'hotels';$allowed=['hotels','rooms','routes','schedules','packages','departures','promotions','users'];
if(!in_array($kind,$allowed,true)){http_response_code(404);exit('Catalogue inconnu.');}
$labels=['hotels'=>'Hébergements','rooms'=>'Chambres','routes'=>'Trajets','schedules'=>'Départs bus & vols','packages'=>'Circuits','departures'=>'Départs circuits','promotions'=>'Promotions','users'=>'Utilisateurs'];
$msg='';$error='';

function voyalo_upload(string $key): ?string {
    if(empty($_FILES[$key])||$_FILES[$key]['error']===UPLOAD_ERR_NO_FILE)return null;
    if($_FILES[$key]['error']!==UPLOAD_ERR_OK||$_FILES[$key]['size']>4*1024*1024)throw new RuntimeException('Image invalide ou supérieure à 4 Mo.');
    $mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES[$key]['tmp_name']);$extensions=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];
    if(!isset($extensions[$mime]))throw new RuntimeException('Formats acceptés : JPG, PNG ou WebP.');
    $name=bin2hex(random_bytes(16)).'.'.$extensions[$mime];$directory=__DIR__.'/../uploads';
    if(!is_dir($directory)&&!mkdir($directory,0755,true)&&!is_dir($directory))throw new RuntimeException('Le dossier de téléversement est indisponible.');
    if(!move_uploaded_file($_FILES[$key]['tmp_name'],$directory.'/'.$name))throw new RuntimeException('Impossible d’enregistrer cette image.');
    return '/uploads/'.$name;
}
function valid_date(string $date): bool { $d=DateTime::createFromFormat('Y-m-d',$date);return $d&&$d->format('Y-m-d')===$date; }
function future_date(string $date): bool { return valid_date($date)&&$date>=date('Y-m-d'); }
function valid_time(string $time): bool { return preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/',$time)===1; }
function post_text(string $key,int $max,bool $required=false): string { $value=trim((string)($_POST[$key]??''));$length=function_exists('mb_strlen')?mb_strlen($value,'UTF-8'):strlen($value);if(($required&&$value==='')||$length>$max)throw new RuntimeException('Vérifiez le contenu des champs obligatoires et leurs longueurs.');return $value; }

if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$command=$_POST['command']??'create';
    try{
        if($command==='update'){
            $id=(int)($_POST['id']??0);
            if($kind==='hotels'){$image=voyalo_upload('image');$q=$pdo->prepare('UPDATE hotels SET nom=?,ville=?,adresse=?,description=?,etoiles=?,image_principale=COALESCE(?,image_principale) WHERE id=?');$q->execute([post_text('nom',180,true),post_text('ville',120,true),post_text('adresse',255,true),post_text('description',10000),max(1,min(5,(int)($_POST['etoiles']??3))),$image,$id]);}
            elseif($kind==='rooms'){$capacity=max(1,(int)($_POST['capacite']??1));$q=$pdo->prepare("SELECT COALESCE(MAX(nb_personnes),0) FROM room_bookings WHERE room_id=? AND statut IN ('en_attente','confirmee','payee') AND date_depart>=CURDATE()");$q->execute([$id]);if($capacity<(int)$q->fetchColumn())throw new RuntimeException('La capacité ne peut pas être inférieure au nombre de voyageurs des séjours réservés.');$image=voyalo_upload('image');$q=$pdo->prepare('UPDATE rooms SET type=?,capacite=?,prix_nuit=?,image=COALESCE(?,image) WHERE id=?');$q->execute([post_text('type',100,true),$capacity,max(0,(int)($_POST['prix_nuit']??0)),$image,$id]);}
            elseif($kind==='routes'){$newCapacity=max(1,(int)($_POST['places_totales']??1));$q=$pdo->prepare('SELECT COALESCE(MAX(vendues),0) FROM (SELECT COALESCE(SUM(b.nb_billets),0) vendues FROM trips_schedule s LEFT JOIN ticket_bookings b ON b.schedule_id=s.id WHERE s.route_id=? GROUP BY s.id) sold');$q->execute([$id]);if($newCapacity<(int)$q->fetchColumn())throw new RuntimeException('La capacité ne peut pas être inférieure aux billets déjà vendus.');$transport=$_POST['type_transport']??'bus';if(!in_array($transport,['bus','avion'],true))throw new RuntimeException('Type de transport invalide.');$q=$pdo->prepare('UPDATE routes SET origine=?,destination=?,type_transport=?,compagnie=?,prix=?,places_totales=? WHERE id=?');$q->execute([post_text('origine',120,true),post_text('destination',120,true),$transport,post_text('compagnie',160,true),max(0,(int)($_POST['prix']??0)),$newCapacity,$id]);}
            elseif($kind==='schedules'){$date=$_POST['date_depart']??'';$time=$_POST['heure_depart']??'';if(!future_date($date)||!valid_time($time))throw new RuntimeException('Date ou heure de départ invalide.');$q=$pdo->prepare('UPDATE trips_schedule SET date_depart=?,heure_depart=? WHERE id=?');$q->execute([$date,$time.':00',$id]);}
            elseif($kind==='packages'){$image=voyalo_upload('image');$q=$pdo->prepare('UPDATE packages SET titre=?,description=?,duree_jours=?,prix=?,itineraire=?,image_principale=COALESCE(?,image_principale) WHERE id=?');$q->execute([post_text('titre',180,true),post_text('description',10000),max(1,(int)($_POST['duree_jours']??1)),max(0,(int)($_POST['prix']??0)),post_text('itineraire',10000),$image,$id]);}
            elseif($kind==='departures'){$date=$_POST['date_depart']??'';if(!future_date($date))throw new RuntimeException('Date de départ invalide.');$pdo->beginTransaction();$q=$pdo->prepare('SELECT (SELECT COALESCE(SUM(b.nb_participants),0) FROM package_bookings b WHERE b.departure_id=d.id) vendues FROM package_departures d WHERE d.id=? FOR UPDATE');$q->execute([$id]);$sold=$q->fetch();if(!$sold)throw new RuntimeException('Départ introuvable.');$total=max(0,(int)($_POST['places']??0));if($total<(int)$sold['vendues'])throw new RuntimeException('La capacité ne peut pas être inférieure aux places déjà réservées.');$q=$pdo->prepare('UPDATE package_departures SET date_depart=?,places=? WHERE id=?');$q->execute([$date,$total-(int)$sold['vendues'],$id]);$pdo->commit();}
            elseif($kind==='promotions'){$q=$pdo->prepare('UPDATE promotions SET code=?,reduction_pct=?,date_debut=?,date_fin=? WHERE id=?');$q->execute([strtoupper(post_text('code',40,true)),min(100,max(0,(float)($_POST['reduction_pct']??0))),($_POST['date_debut']??'')?:null,($_POST['date_fin']??'')?:null,$id]);}
            else throw new RuntimeException('Modification non disponible pour ce type de fiche.');$msg='Modifications enregistrées.';
        }elseif($command==='toggle'){
            $id=(int)($_POST['id']??0);
            $targets=['hotels'=>['hotels','actif'],'rooms'=>['rooms','disponible'],'routes'=>['routes','actif'],'packages'=>['packages','actif'],'promotions'=>['promotions','actif']];
            if(!isset($targets[$kind]))throw new RuntimeException('Action non permise.');[$table,$column]=$targets[$kind];$q=$pdo->prepare("UPDATE $table SET $column=IF($column=1,0,1) WHERE id=?");$q->execute([$id]);$msg='Disponibilité mise à jour.';
        }elseif($command==='role'&&$kind==='users'){
            $id=(int)($_POST['id']??0);$role=$_POST['role']??'';if(!in_array($role,['client','agent','admin'],true))throw new RuntimeException('Rôle invalide.');if($id===(int)user()['id']&&$role!=='admin')throw new RuntimeException('Vous ne pouvez pas retirer votre propre accès administrateur.');$q=$pdo->prepare('UPDATE users SET role=? WHERE id=?');$q->execute([$role,$id]);$msg='Rôle utilisateur mis à jour.';
        }elseif($command==='seats'&&$kind==='schedules'){
            $id=(int)($_POST['id']??0);$pdo->beginTransaction();$q=$pdo->prepare('SELECT r.places_totales,(SELECT COALESCE(SUM(b.nb_billets),0) FROM ticket_bookings b WHERE b.schedule_id=s.id) vendues FROM trips_schedule s JOIN routes r ON r.id=s.route_id WHERE s.id=? FOR UPDATE');$q->execute([$id]);$capacity=$q->fetch();if(!$capacity)throw new RuntimeException('Départ introuvable.');$max=max(0,(int)$capacity['places_totales']-(int)$capacity['vendues']);$seats=min($max,max(0,(int)($_POST['places_restantes']??0)));$q=$pdo->prepare('UPDATE trips_schedule SET places_restantes=? WHERE id=?');$q->execute([$seats,$id]);$pdo->commit();$msg='Places restantes mises à jour sans dépasser les billets déjà vendus.';
        }elseif($command==='departure_seats'&&$kind==='departures'){
            $id=(int)($_POST['id']??0);$pdo->beginTransaction();$q=$pdo->prepare('SELECT (SELECT COALESCE(SUM(b.nb_participants),0) FROM package_bookings b WHERE b.departure_id=d.id) vendues FROM package_departures d WHERE d.id=? FOR UPDATE');$q->execute([$id]);$sold=$q->fetch();if(!$sold)throw new RuntimeException('Départ introuvable.');$capacity=max(0,(int)($_POST['places']??0));$q=$pdo->prepare('UPDATE package_departures SET places=? WHERE id=?');$q->execute([max(0,$capacity-(int)$sold['vendues']),$id]);$pdo->commit();$msg='Places disponibles mises à jour.';
        }elseif($kind==='hotels'){
            $image=voyalo_upload('image');$equip=array_values(array_filter(array_map('trim',explode(',',post_text('equipements',1000)))));$json=json_encode($equip,JSON_UNESCAPED_UNICODE);$stars=max(1,min(5,(int)($_POST['etoiles']??3)));
            $q=$pdo->prepare('INSERT INTO hotels(nom,ville,adresse,description,etoiles,image_principale,equipements) VALUES(?,?,?,?,?,?,?)');$q->execute([post_text('nom',180,true),post_text('ville',120,true),post_text('adresse',255,true),post_text('description',10000),$stars,$image,$json]);$msg='Hébergement ajouté. Ajoutez ses chambres depuis l’onglet Chambres.';
        }elseif($kind==='rooms'){
            $hotel=(int)($_POST['hotel_id']??0);$image=voyalo_upload('image');$q=$pdo->prepare('INSERT INTO rooms(hotel_id,type,capacite,prix_nuit,disponible,image) SELECT id,?,?,?,?,? FROM hotels WHERE id=? AND actif=1');$q->execute([post_text('type',100,true),max(1,(int)($_POST['capacite']??1)),max(0,(int)($_POST['prix_nuit']??0)),(int)($_POST['disponible']??1),$image,$hotel]);if(!$q->rowCount())throw new RuntimeException('Sélectionnez un hôtel actif.');$msg='Chambre ajoutée.';
        }elseif($kind==='routes'){
            $transport=$_POST['type_transport']??'bus';if(!in_array($transport,['bus','avion'],true))throw new RuntimeException('Type de transport invalide.');$pdo->beginTransaction();$places=max(1,(int)($_POST['places_totales']??1));$q=$pdo->prepare('INSERT INTO routes(origine,destination,type_transport,compagnie,prix,places_totales) VALUES(?,?,?,?,?,?)');$q->execute([post_text('origine',120,true),post_text('destination',120,true),$transport,post_text('compagnie',160,true),max(0,(int)($_POST['prix']??0)),$places]);$route=(int)$pdo->lastInsertId();$date=$_POST['date_depart']??'';$time=$_POST['heure_depart']??'';if($date!==''||$time!==''){if(!future_date($date)||!valid_time($time))throw new RuntimeException('Date ou heure de départ invalide.');$q=$pdo->prepare('INSERT INTO trips_schedule(route_id,date_depart,heure_depart,places_restantes) VALUES(?,?,?,?)');$q->execute([$route,$date,$time.':00',$places]);}$pdo->commit();$msg='Trajet ajouté'.($date&&$time?' et départ programmé.':'.');
        }elseif($kind==='schedules'){
            $route=(int)($_POST['route_id']??0);$date=$_POST['date_depart']??'';$time=$_POST['heure_depart']??'';if(!future_date($date)||!valid_time($time))throw new RuntimeException('Date ou heure de départ invalide.');$q=$pdo->prepare('INSERT INTO trips_schedule(route_id,date_depart,heure_depart,places_restantes) SELECT id,?,?,places_totales FROM routes WHERE id=? AND actif=1');$q->execute([$date,$time.':00',$route]);if(!$q->rowCount())throw new RuntimeException('Sélectionnez un trajet actif.');$msg='Départ ajouté.';
        }elseif($kind==='packages'){
            $pdo->beginTransaction();$q=$pdo->prepare('INSERT INTO packages(titre,description,duree_jours,prix,itineraire,image_principale) VALUES(?,?,?,?,?,?)');$q->execute([post_text('titre',180,true),post_text('description',10000),max(1,(int)($_POST['duree_jours']??1)),max(0,(int)($_POST['prix']??0)),post_text('itineraire',10000),voyalo_upload('image')]);$package=(int)$pdo->lastInsertId();$date=$_POST['date_depart']??'';if($date!==''){if(!future_date($date))throw new RuntimeException('Date de départ invalide.');$q=$pdo->prepare('INSERT INTO package_departures(package_id,date_depart,places) VALUES(?,?,?)');$q->execute([$package,$date,max(1,(int)($_POST['places']??20))]);}$pdo->commit();$msg='Circuit ajouté'.($date?' avec son premier départ.':'.');
        }elseif($kind==='departures'){
            $package=(int)($_POST['package_id']??0);$date=$_POST['date_depart']??'';if(!future_date($date))throw new RuntimeException('Date de départ invalide.');$q=$pdo->prepare('INSERT INTO package_departures(package_id,date_depart,places) SELECT id,?,? FROM packages WHERE id=? AND actif=1');$q->execute([$date,max(1,(int)($_POST['places']??20)),$package]);if(!$q->rowCount())throw new RuntimeException('Sélectionnez un circuit actif.');$msg='Départ de circuit ajouté.';
        }elseif($kind==='promotions'){
            $q=$pdo->prepare('INSERT INTO promotions(code,reduction_pct,date_debut,date_fin) VALUES(?,?,?,?)');$q->execute([strtoupper(post_text('code',40,true)),min(100,max(0,(float)($_POST['reduction_pct']??0))),($_POST['date_debut']??'')?:null,($_POST['date_fin']??'')?:null]);$msg='Code promotionnel ajouté.';
        }elseif($kind==='users'){
            $name=post_text('nom',120,true);$email=filter_var(strtolower(trim($_POST['email']??'')),FILTER_VALIDATE_EMAIL);$password=$_POST['password']??'';if(!$email||strlen($password)<12)throw new RuntimeException('Renseignez un email valide et un mot de passe de 12 caractères minimum.');$q=$pdo->prepare("INSERT INTO users(nom,email,password,telephone,role) VALUES(?,?,?,?, 'agent')");$q->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT),post_text('telephone',30)]);$msg='Compte agent créé.';
        }
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e instanceof RuntimeException?$e->getMessage():'Enregistrement impossible. Vérifiez les données saisies et les doublons.';}
}

$hotels=$pdo->query('SELECT id,nom,ville FROM hotels WHERE actif=1 ORDER BY ville,nom')->fetchAll();$routes=$pdo->query('SELECT id,origine,destination,compagnie,places_totales FROM routes WHERE actif=1 ORDER BY origine,destination')->fetchAll();$packages=$pdo->query('SELECT id,titre FROM packages WHERE actif=1 ORDER BY titre')->fetchAll();
$queries=[
 'hotels'=>'SELECT id,nom,ville,adresse,etoiles,actif FROM hotels ORDER BY id DESC LIMIT 100',
 'rooms'=>'SELECT rm.id,h.nom hotel,rm.type,rm.capacite,rm.prix_nuit,rm.disponible FROM rooms rm JOIN hotels h ON h.id=rm.hotel_id ORDER BY rm.id DESC LIMIT 100',
 'routes'=>'SELECT id,origine,destination,type_transport,compagnie,prix,places_totales,actif FROM routes ORDER BY id DESC LIMIT 100',
 'schedules'=>'SELECT s.id,CONCAT(r.origine,\' → \',r.destination) trajet,r.compagnie,s.date_depart,s.heure_depart,s.places_restantes,r.places_totales FROM trips_schedule s JOIN routes r ON r.id=s.route_id ORDER BY s.date_depart DESC,s.heure_depart DESC LIMIT 100',
 'packages'=>'SELECT id,titre,duree_jours,prix,actif FROM packages ORDER BY id DESC LIMIT 100',
 'departures'=>'SELECT d.id,p.titre circuit,d.date_depart,d.places places_restantes,d.places+(SELECT COALESCE(SUM(b.nb_participants),0) FROM package_bookings b WHERE b.departure_id=d.id) capacite_totale FROM package_departures d JOIN packages p ON p.id=d.package_id ORDER BY d.date_depart DESC LIMIT 100',
 'promotions'=>'SELECT id,code,reduction_pct,date_debut,date_fin,actif FROM promotions ORDER BY id DESC LIMIT 100',
 'users'=>'SELECT id,nom,email,telephone,role,created_at FROM users ORDER BY id DESC LIMIT 100'
];$rows=$pdo->query($queries[$kind])->fetchAll();$title='Gestion · '.$labels[$kind];require __DIR__.'/../includes/header.php';
?>
<section class="max-w-7xl mx-auto px-4 pb-12"><div class="page-heading"><p class="page-eyebrow">Administration · Catalogue</p><h1 class="page-title"><?=e($labels[$kind])?></h1><p class="page-subtitle">Ajoutez, actualisez et publiez les offres de Voyalo.</p></div>
<nav class="flex gap-2 overflow-x-auto pb-3 admin-tabs" aria-label="Gestion des catalogues"><?php foreach($labels as $key=>$label):?><a class="<?=$kind===$key?'selected':''?>" href="<?=e(app_url('/admin/catalog.php?kind='.$key))?>"><?=e($label)?></a><?php endforeach;?></nav>
<?php if($msg):?><p class="mt-4 bg-emerald-50 text-emerald-800 p-3 rounded-lg" role="status"><?=e($msg)?></p><?php endif;?><?php if($error):?><p class="mt-4 bg-rose-50 text-rose-800 p-3 rounded-lg" role="alert"><?=e($error)?></p><?php endif;?>
<section class="detail-section mt-4"><p class="page-eyebrow">Nouvel élément</p><h2 class="text-xl font-black mt-1"><?php if($kind==='hotels'):?>Ajouter un hébergement<?php elseif($kind==='rooms'):?>Ajouter une chambre<?php elseif($kind==='routes'):?>Ajouter un trajet<?php elseif($kind==='schedules'):?>Programmer un départ<?php elseif($kind==='packages'):?>Ajouter un circuit<?php elseif($kind==='departures'):?>Ajouter une date de circuit<?php elseif($kind==='promotions'):?>Créer une promotion<?php else:?>Créer un compte agent<?php endif;?></h2>
<form method="post" enctype="multipart/form-data" class="admin-create-form mt-5"><?=csrf_field()?><input type="hidden" name="command" value="create">
<?php if($kind==='hotels'):?><div><label>Nom de l'hôtel</label><input name="nom" maxlength="180" required></div><div><label>Ville</label><input name="ville" maxlength="120" required placeholder="Douala, Yaoundé, Kribi…"></div><div><label>Adresse</label><input name="adresse" maxlength="255" required></div><div><label>Étoiles</label><select name="etoiles"><option value="1">1 étoile</option><option value="2">2 étoiles</option><option value="3" selected>3 étoiles</option><option value="4">4 étoiles</option><option value="5">5 étoiles</option></select></div><div class="span-2"><label>Description</label><textarea name="description" rows="3"></textarea></div><div class="span-2"><label>Équipements <span class="text-slate-500 font-normal">(séparés par des virgules)</span></label><input name="equipements" placeholder="Wi-Fi, piscine, restaurant"></div><div><label>Photo principale</label><input type="file" name="image" accept="image/jpeg,image/png,image/webp"></div>
<?php elseif($kind==='rooms'):?><div><label>Hôtel</label><select name="hotel_id" required><option value="">Sélectionner un hôtel</option><?php foreach($hotels as $h):?><option value="<?=$h['id']?>"><?=e($h['nom'].' · '.$h['ville'])?></option><?php endforeach;?></select></div><div><label>Type de chambre</label><input name="type" maxlength="100" required placeholder="Chambre double"></div><div><label>Capacité</label><input name="capacite" type="number" min="1" max="50" value="2" required></div><div><label>Prix par nuit (FCFA)</label><input name="prix_nuit" type="number" min="0" required></div><div><label>État</label><select name="disponible"><option value="1">Disponible</option><option value="0">Masquer pour le moment</option></select></div><div><label>Photo de la chambre</label><input type="file" name="image" accept="image/jpeg,image/png,image/webp"></div>
<?php elseif($kind==='routes'):?><div><label>Origine</label><input name="origine" maxlength="120" required></div><div><label>Destination</label><input name="destination" maxlength="120" required></div><div><label>Transport</label><select name="type_transport"><option value="bus">Bus</option><option value="avion">Avion</option></select></div><div><label>Compagnie</label><input name="compagnie" maxlength="160" required></div><div><label>Tarif par billet (FCFA)</label><input name="prix" type="number" min="0" required></div><div><label>Capacité totale</label><input name="places_totales" type="number" min="1" required></div><div><label>Date du premier départ <span class="text-slate-500 font-normal">(facultatif)</span></label><input type="date" name="date_depart" min="<?=date('Y-m-d')?>"></div><div><label>Heure de départ</label><input type="time" name="heure_depart"></div>
<?php elseif($kind==='schedules'):?><div><label>Trajet</label><select name="route_id" required><option value="">Sélectionner un trajet</option><?php foreach($routes as $r):?><option value="<?=$r['id']?>"><?=e($r['origine'].' → '.$r['destination'].' · '.$r['compagnie'])?></option><?php endforeach;?></select></div><div><label>Date de départ</label><input type="date" name="date_depart" min="<?=date('Y-m-d')?>" required></div><div><label>Heure</label><input type="time" name="heure_depart" required></div>
<?php elseif($kind==='packages'):?><div><label>Titre du circuit</label><input name="titre" maxlength="180" required></div><div><label>Durée (jours)</label><input name="duree_jours" type="number" min="1" required></div><div><label>Prix par personne (FCFA)</label><input name="prix" type="number" min="0" required></div><div><label>Places pour le premier départ</label><input name="places" type="number" min="1" value="20"></div><div><label>Date du premier départ <span class="text-slate-500 font-normal">(facultatif)</span></label><input type="date" name="date_depart" min="<?=date('Y-m-d')?>"></div><div><label>Photo principale</label><input type="file" name="image" accept="image/jpeg,image/png,image/webp"></div><div class="span-2"><label>Description</label><textarea name="description" rows="3"></textarea></div><div class="span-2"><label>Itinéraire</label><textarea name="itineraire" rows="3"></textarea></div>
<?php elseif($kind==='departures'):?><div><label>Circuit</label><select name="package_id" required><option value="">Sélectionner un circuit</option><?php foreach($packages as $p):?><option value="<?=$p['id']?>"><?=e($p['titre'])?></option><?php endforeach;?></select></div><div><label>Date de départ</label><input type="date" name="date_depart" min="<?=date('Y-m-d')?>" required></div><div><label>Places disponibles</label><input type="number" name="places" min="1" value="20" required></div>
<?php elseif($kind==='promotions'):?><div><label>Code</label><input name="code" maxlength="40" required placeholder="VOYALO10"></div><div><label>Réduction (%)</label><input name="reduction_pct" type="number" min="0.01" max="100" step="0.01" required></div><div><label>Valide du</label><input type="date" name="date_debut"></div><div><label>Valide jusqu'au</label><input type="date" name="date_fin"></div>
<?php else:?> <div><label>Nom complet</label><input name="nom" maxlength="120" required></div><div><label>Email</label><input type="email" name="email" maxlength="190" required></div><div><label>Téléphone</label><input name="telephone" maxlength="30"></div><div><label>Mot de passe provisoire</label><input type="password" name="password" minlength="12" required><small class="text-slate-500">12 caractères minimum. Communiquez-le au nouvel agent de façon sécurisée.</small></div><?php endif;?>
<button class="btn span-all">Ajouter et enregistrer</button></form></section>

<div class="flex justify-between items-end mt-10 gap-3"><div><p class="page-eyebrow">Catalogue actuel</p><h2 class="text-2xl font-black mt-1"><?=count($rows)?> élément<?=count($rows)===1?'':'s'?></h2></div></div><div class="table-wrap mt-4"><table><thead><tr><?php foreach(array_keys($rows[0]??['id'=>'']) as $column):?><th><?=e($column)?></th><?php endforeach;?><?php if($kind!=='users'):?><th>État</th><?php else:?><th>Rôle</th><?php endif;?></tr></thead><tbody><?php foreach($rows as $row):?><tr><?php foreach($row as $column=>$value):?><td><?php if(in_array($column,['actif','disponible'],true)):?><span class="status-pill"><?=$value?'Actif':'Masqué'?></span><?php elseif($column==='image_principale'||$column==='image'):?><?= $value?'<a class="text-teal-800 underline" href="'.e((string)$value).'" target="_blank" rel="noopener">Voir la photo</a>':'—' ?><?php else:?><?=e((string)$value)?><?php endif;?></td><?php endforeach;?>
<?php if($kind==='users'):?><td><form method="post" class="inline-admin-form"><?=csrf_field()?><input type="hidden" name="command" value="role"><input type="hidden" name="id" value="<?=$row['id']?>"><select name="role" aria-label="Rôle de <?=e($row['nom'])?>"><?php foreach(['client','agent','admin'] as $role):?><option value="<?=$role?>" <?=$row['role']===$role?'selected':''?>><?=$role?></option><?php endforeach;?></select><button class="btn btn-small">Enregistrer</button></form></td>
<?php elseif(in_array($kind,['hotels','rooms','routes','packages','schedules','departures','promotions'],true)):?><td><details class="admin-editor"><summary>Modifier</summary><form method="post" enctype="multipart/form-data" class="admin-edit-form"><?=csrf_field()?><input type="hidden" name="command" value="update"><input type="hidden" name="id" value="<?=$row['id']?>">
<?php if($kind==='hotels'):?><label>Nom<input name="nom" value="<?=e($row['nom'])?>" required></label><label>Ville<input name="ville" value="<?=e($row['ville'])?>" required></label><label>Adresse<input name="adresse" value="<?=e($row['adresse'])?>" required></label><label>Étoiles<input type="number" name="etoiles" min="1" max="5" value="<?=$row['etoiles']?>"></label><label>Description<textarea name="description" rows="2"></textarea></label><label>Remplacer la photo<input type="file" name="image" accept="image/jpeg,image/png,image/webp"></label>
<?php elseif($kind==='rooms'):?><label>Type<input name="type" value="<?=e($row['type'])?>" required></label><label>Capacité<input type="number" name="capacite" min="1" value="<?=$row['capacite']?>"></label><label>Prix / nuit<input type="number" name="prix_nuit" min="0" value="<?=$row['prix_nuit']?>"></label><label>Remplacer la photo<input type="file" name="image" accept="image/jpeg,image/png,image/webp"></label>
<?php elseif($kind==='routes'):?><label>Origine<input name="origine" value="<?=e($row['origine'])?>" required></label><label>Destination<input name="destination" value="<?=e($row['destination'])?>" required></label><label>Transport<select name="type_transport"><option value="bus" <?=$row['type_transport']==='bus'?'selected':''?>>Bus</option><option value="avion" <?=$row['type_transport']==='avion'?'selected':''?>>Avion</option></select></label><label>Compagnie<input name="compagnie" value="<?=e($row['compagnie'])?>" required></label><label>Prix<input type="number" name="prix" min="0" value="<?=$row['prix']?>"></label><label>Places totales<input type="number" name="places_totales" min="1" value="<?=$row['places_totales']?>"></label>
<?php elseif($kind==='schedules'):?><label>Date<input type="date" name="date_depart" value="<?=e($row['date_depart'])?>" required></label><label>Heure<input type="time" name="heure_depart" value="<?=e(substr($row['heure_depart'],0,5))?>" required></label>
<?php elseif($kind==='packages'):?><label>Titre<input name="titre" value="<?=e($row['titre'])?>" required></label><label>Durée (jours)<input type="number" name="duree_jours" min="1" value="<?=$row['duree_jours']?>"></label><label>Prix<input type="number" name="prix" min="0" value="<?=$row['prix']?>"></label><label>Description<textarea name="description" rows="2"><?=e($row['description']??'')?></textarea></label><label>Itinéraire<textarea name="itineraire" rows="2"><?=e($row['itineraire']??'')?></textarea></label><label>Remplacer la photo<input type="file" name="image" accept="image/jpeg,image/png,image/webp"></label>
<?php elseif($kind==='departures'):?><label>Date<input type="date" name="date_depart" value="<?=e($row['date_depart'])?>" required></label><label>Capacité totale<input type="number" name="places" min="0" value="<?=$row['capacite_totale']?>"></label>
<?php else:?><label>Code<input name="code" value="<?=e($row['code'])?>" required></label><label>Réduction (%)<input type="number" name="reduction_pct" min="0" max="100" step="0.01" value="<?=$row['reduction_pct']?>"></label><label>Valide du<input type="date" name="date_debut" value="<?=e($row['date_debut']??'')?>"></label><label>Valide jusqu'au<input type="date" name="date_fin" value="<?=e($row['date_fin']??'')?>"></label><?php endif;?>
<button class="btn btn-small">Enregistrer</button></form></details><div class="mt-2"><?php if(in_array($kind,['hotels','rooms','routes','packages','promotions'],true)):?><form method="post"><?=csrf_field()?><input type="hidden" name="command" value="toggle"><input type="hidden" name="id" value="<?=$row['id']?>"><button class="btn btn-small <?=$row[$kind==='rooms'?'disponible':'actif']?'btn-warning':''?>"><?=$row[$kind==='rooms'?'disponible':'actif']?'Masquer':'Publier'?></button></form><?php elseif($kind==='schedules'):?><form method="post" class="inline-admin-form"><?=csrf_field()?><input type="hidden" name="command" value="seats"><input type="hidden" name="id" value="<?=$row['id']?>"><input type="number" name="places_restantes" min="0" max="<?=$row['places_totales']?>" value="<?=$row['places_restantes']?>" aria-label="Places restantes"><button class="btn btn-small">Places</button></form><?php endif;?></div></td><?php endif;?></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="8">Aucun élément dans ce catalogue pour le moment.</td></tr><?php endif;?></tbody></table></div></section>
<?php require __DIR__.'/../includes/footer.php';?>
